#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

cp "/tmp/PegasusController_X2/focuserlist PegasusController.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp "/tmp/PegasusController_X2/PegasusController.ui" "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/"
cp "/tmp/PegasusController_X2/PegasusAstro.png" "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/"
cp "/tmp/PegasusController_X2/libPegasusController.dylib" "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/focuserlist PegasusController.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/PegasusController.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/PegasusAstro.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/FocuserPlugIns/libPegasusController.dylib"
fi

rm -rf /tmp/PegasusController_X2

